networks:
  net-db:
    driver: bridge
    external: true
  net-nginx:
    driver: bridge
    external: true
  net-hijo-internal:
    driver: bridge
    external: true    
  net-fed-internal:
    driver: bridge 
    external: true

volumes:
  ckan_storage:
  pip_cache:
  site_packages: 
  solr_data:
  datapusher_data:
    
services:   
  solr:
    build:
      context: ../docker_solr/solr_image/
      dockerfile: Dockerfile  
    image: CKAN/ckan-solr:2.10-solr9
    command: solr-precreate ckan
    volumes:
      - solr_data:/var/solr
    networks:
      - net-db
      - net-hijo-internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8983/solr"]
      interval: 10s
      timeout: 5s
      retries: 5 

  redis:
    build:
      context: ../docker_redis/redis-image/
      dockerfile: Dockerfile 
    image: CKAN/redis:7
    networks:
      - net-hijo-internal
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"] 
      
  datapusher:
    networks:
      - net-db
      - net-hijo-internal       
    build:
      context: ../docker_datapusher/datapusher_images/
      dockerfile: Dockerfile   
    image: ckan/ckan-base-datapusher:0.0.21    
    volumes:
      - datapusher_data:/srv/app/src/datapusher
      - /usr/lib/ckan/default/src/ValleData/docker_datapusher/datapusher_images/deployment/datapusher-uwsgi.ini:/srv/app/src/datapusher/deployment/datapusher-uwsgi.ini
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/8800' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3        
      
  ckan:
    image: CKAN/ckan:2.11.4  
    depends_on:      
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy   
      datapusher:
        condition: service_healthy
    environment:
      # 1. Fuerza a uWSGI/Python a leer este archivo
      - CKAN_INI=/srv/app/ckan.ini
      # 2. Refuerza el dominio exterior directo en el entorno
      - CKAN_SITE_URL=http://alcala.gobernaciondelvalle.gov.co    
    ports:
      - "5000:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
      - pip_cache:/root/.cache/pip
      - site_packages:/usr/lib/python3.10/site-packages
      - /usr/lib/ckan/default/src/ValleData/alcala-ckan/config/ckan.ini:/srv/app/ckan.ini
      - /usr/lib/ckan/default/src/ValleData/alcala-ckan/config/ckan.ini:/srv/app/src/deployment/ckan.ini
      - /usr/lib/ckan/default/src/ValleData/alcala-ckan/deployment/ckan-uwsgi.ini:/srv/app/src/deployment/ckan-uwsgi.ini
    restart: unless-stopped  
    networks:
      - net-nginx 
      - net-db
      - net-hijo-internal
      - net-fed-internal     
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://ckan:5000/api/3/action/status_show"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s       
  