# Aceptar conexiones desde cualquier red (dentro de Docker)
bind 0.0.0.0

# Puerto por defecto
port 6379

# --- SEGURIDAD ---
# Descomenta la línea de abajo para poner contraseña
# requirepass TuClaveSeguraAqui

# --- MEMORIA ---
# Limitar a 512MB (ajusta según tu servidor)
maxmemory 512mb
# Cuando se llene, borrar la llave que lleva más tiempo sin usarse (LRU)
maxmemory-policy allkeys-lru

# --- PERSISTENCIA ---
# Guardar si hay 1 cambio cada 15 minutos
save 900 1
# Guardar si hay 10 cambios cada 5 minutos
save 300 10
appendonly yes
