name: Validar Extensiones
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          # Aquí instalas tu core y extensiones
          pip install -e ./ckan 
          pip install -r requirements.txt
