networks:
  net-db:
    driver: bridge
    external: true
  net-nginx:
    driver: bridge
    external: true
  net-hijo-internal:
    driver: bridge
    external: true    
  net-fed-internal:
    driver: bridge 
    external: true

volumes:
  ckan_storage:
  pip_cache:
  site_packages: 
  solr_data:
  datapusher_data:
    
services:   
  solr:
    build:
      context: docker_solr/solr_image/
      dockerfile: Dockerfile  
    image: CKAN/ckan-solr:2.10-solr9
    command: solr-precreate ckan
    volumes:
      - solr_data:/var/solr
    networks:
      - net-db
      - net-hijo-internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8983/solr"]
      interval: 10s
      timeout: 5s
      retries: 5 

  redis:
    build:
      context: docker_redis/redis-image/
      dockerfile: Dockerfile 
    image: CKAN/redis:7
    networks:
      - net-hijo-internal
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"] 
      
  datapusher:
    networks:
      - net-db
      - net-hijo-internal 
      
    build:
      context: docker_datapusher/datapusher_images/
      dockerfile: Dockerfile   
    image: ckan/ckan-base-datapusher:0.0.21    
    volumes:
      - datapusher_data:/srv/app/datapusher-src
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/8800' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3        
      
  ckan:
    image: CKAN/ckan:2.11.4  
    depends_on:      
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy   
      datapusher:
        condition: service_healthy   
    environment:
      - CKAN_SITE_ID
      - CKAN_SECRET_KEY
      - CKAN_SITE_URL
      - CKAN_SQLALCHEMY_URL
      - CKAN_DATASTORE_WRITE_URL
      - CKAN_DATASTORE_READ_URL
      - CKAN_BEAKER__SESSION__SECRET
      - CKAN_API_TOKEN__JWT__ENCODE__SECRET
      - CKAN_API_TOKEN__JWT__DECODE__SECRET
      - CKAN_SOLR_URL
      - CKAN_REDIS_URL
      - CKAN_DATAPUSHER_URL
      - CKAN__DATAPUSHER__CALLBACK_URL_BASE
      - CKAN__PLUGINS
      - DATAPUSHER_API_TOKEN
    env_file:
      - .env       
    ports:
      - "5000:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
      - pip_cache:/root/.cache/pip
      - site_packages:/usr/lib/python3.10/site-packages
    restart: unless-stopped  
    networks:
      - net-nginx 
      - net-db
      - net-hijo-internal
      - net-fed-internal     
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://ckan:5000/api/3/action/status_show"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s       
  