networks:
  ckan-hijo-net:
    name: ckan-hijo-net
    driver: bridge
    external: true    
    
volumes:
  datapusher_data:  
  
services:
  datapusher:
    networks:
      - ckan-hijo-net  
    image: ckan/ckan-base-datapusher:0.0.21
    environment:
      DATAPUSHER_API_TOKEN: ${DATAPUSHER_API_TOKEN}
    volumes:
      - datapusher_data:/srv/app/datapusher-src
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/8800' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3