networks:
  # Redes para el CKAN Federado (Principal)
  net-fed-internal:
    driver: bridge
    external: true
  
  # Redes para el CKAN Hijo
  net-hijo-internal:
    driver: bridge
    external: true

  # Red común solo para la entrada de Nginx
  net-nginx:
    driver: bridge
    external: true
    
  # DB Externo
  net-db:
    driver: bridge 
    external: true    

volumes:
  harvest_ckan_storage:
  harvest_pip_cache:
  harvest_site_packages: 
  harvest_solr_data:
    
services:   
  solr:
    image: CKAN/ckan-solr:2.10-solr9
    command: solr-precreate ckan
    volumes:
      - harvest_solr_data:/var/solr
    networks:
      - net-fed-internal
      - net-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8983/solr"]
      interval: 10s
      timeout: 5s
      retries: 5 

  redis:
    image: CKAN/redis:7
    networks:
      - net-fed-internal
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"] 
      
      
  harvest:
    image: Harvest/ckan:2.11.4  
    depends_on:      
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy 
    environment:
      # 1. Fuerza a uWSGI/Python a leer este archivo
      - CKAN_INI=/srv/app/ckan.ini
      # 2. Refuerza el dominio exterior directo en el entorno
      - CKAN_SITE_URL=http://harvest.gobernaciondelvalle.gov.co       
    ports:
      - "5100:5000"
    volumes:
      - harvest_ckan_storage:/var/lib/ckan
      - harvest_pip_cache:/root/.cache/pip
      - harvest_site_packages:/usr/lib/python3.10/site-packages
      - /usr/lib/ckan/default/src/ValleData/harvest/config/ckan.ini:/srv/app/ckan.ini
      - /usr/lib/ckan/default/src/ValleData/harvest/config/ckan.ini:/srv/app/src/deployment/ckan.ini
      - /usr/lib/ckan/default/src/ValleData/harvest/deployment/ckan-uwsgi.ini:/srv/app/src/deployment/ckan-uwsgi.ini
    restart: unless-stopped  
    networks:
      - net-fed-internal
      - net-db
      - net-nginx 
      - net-hijo-internal             
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://harvest-harvest-1:5000/api/3/action/status_show"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s       
  
  worker:
    networks:
      - net-fed-internal
      - net-db
      - net-hijo-internal
    image: Harvest/ckan:2.11.4        
    command: ckan -c /srv/app/ckan.ini harvester run
    volumes:
      - /usr/lib/ckan/default/src/ValleData/harvest/config/ckan.ini:/srv/app/ckan.ini 
    depends_on:
      harvest:
        condition: service_healthy
      redis:
        condition: service_healthy      
    restart: unless-stopped  
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://harvest-harvest-1:5000/api/3/action/status_show"]
      interval: 60s
      timeout: 10s
      retries: 3   

  harvest-gather:
    networks:
      - net-fed-internal
      - net-db
      - net-hijo-internal
    image: Harvest/ckan:2.11.4   
    depends_on:
      harvest:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - /usr/lib/ckan/default/src/ValleData/harvest/config/ckan.ini:/srv/app/ckan.ini      
    command: ckan -c /srv/app/ckan.ini harvester gather-consumer        
    restart: unless-stopped  
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://harvest-harvest-1:5000/api/3/action/status_show"]
      interval: 60s
      timeout: 10s
      retries: 3

  harvest-fetch:
    networks:
      - net-fed-internal
      - net-db
      - net-hijo-internal
    image: Harvest/ckan:2.11.4   
    depends_on:
      harvest:
        condition: service_healthy
      redis:
        condition: service_healthy 
    volumes:
      - /usr/lib/ckan/default/src/ValleData/harvest/config/ckan.ini:/srv/app/ckan.ini     
    command: ckan -c /srv/app/ckan.ini harvester fetch-consumer      
    restart: unless-stopped  
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://harvest-harvest-1:5000/api/3/action/status_show"]
      interval: 60s
      timeout: 10s
      retries: 3      
  