networks:
  net-db:
    driver: bridge
    external: true
  net-nginx:
    driver: bridge
    external: true
  net-hijo-internal:
    driver: bridge
    external: true    
  net-fed-internal:
    driver: bridge 
    external: true

volumes:
  pradera_ckan_storage:
  pradera_pip_cache:
  pradera_site_packages: 
  pradera_solr_data:
  pradera_datapusher_data:
    
services:   
  solr:
    image: CKAN/ckan-solr:2.10-solr9
    command: solr-precreate ckan
    restart: always
    volumes:
      - pradera_solr_data:/var/solr
    networks:
      - net-db
      - net-hijo-internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8983/solr"]
      interval: 10s
      timeout: 5s
      retries: 5 

  redis:
    image: CKAN/redis:7
    networks:
      - net-hijo-internal
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"] 
      
  datapusher:
    networks:
      - net-db
      - net-hijo-internal       
    image: ckan/ckan-base-datapusher:0.0.21   
    # Dentro de tu docker-compose.yml en el servicio datapusher:
    volumes:
      - pradera_datapusher_data:/srv/app/src/datapusher
      - /usr/lib/ckan/default/src/ValleData/docker_datapusher/datapusher_images/deployment/datapusher-uwsgi.ini:/srv/app/src/datapusher/deployment/datapusher-uwsgi.ini
      - /usr/lib/ckan/default/src/ValleData/docker_datapusher/datapusher_images/deployment/datapusher_settings.py:/srv/app/src/datapusher/deployment/datapusher_settings.py
      - /usr/lib/ckan/default/src/ValleData/docker_datapusher/datapusher_images/deployment/datapusher.wsgi:/srv/app/src/datapusher/deployment/datapusher.wsgi
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/8800' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3        
      
  ckan:
    image: CKAN/ckan:2.11.4
    depends_on:      
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy   
      datapusher:
        condition: service_healthy  
    ports:
      - "5001:5000"
    environment:
      - CKAN_INI=/srv/app/ckan.ini  
      - CKAN_SITE_URL=http://pradera.gobernaciondelvalle.gov.co  
      - DATAPUSHER_CKAN_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJrRVFFekttaldfWFNTOWFDcm5BUDJVeW9sc1FVWmlVYVVRbndyY252U0g0IiwiaWF0IjoxNzc5NTM5MjY2fQ.nguhpsHrYxaGZisCMP72nNQSrBNL6CVzLVLkAS-vRzk
    volumes:
      - pradera_ckan_storage:/var/lib/ckan
      - pradera_pip_cache:/root/.cache/pip
      - pradera_site_packages:/usr/lib/python3.10/site_packages
      - /usr/lib/ckan/default/src/ValleData/pradera-ckan/config/ckan.ini:/srv/app/ckan.ini
      - /usr/lib/ckan/default/src/ValleData/pradera-ckan/config/ckan.ini:/srv/app/src/deployment/ckan.ini
      - /usr/lib/ckan/default/src/ValleData/pradera-ckan/deployment/ckan-uwsgi.ini:/srv/app/src/deployment/ckan-uwsgi.ini
    restart: unless-stopped  
    networks:
      - net-nginx 
      - net-db
      - net-hijo-internal
      - net-fed-internal     
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://ckan:5000/api/3/action/status_show"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s       
  
  worker:
    networks:
      - net-fed-internal
      - net-db
      - net-hijo-internal
    image: CKAN/ckan:2.11.4        
    command: ckan -c /srv/app/ckan.ini jobs worker
    volumes:
      - /usr/lib/ckan/default/src/ValleData/pradera-ckan/config/ckan.ini:/srv/app/ckan.ini 
    depends_on:
      ckan:
        condition: service_healthy
      redis:
        condition: service_healthy      
    restart: unless-stopped  
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://pradera-ckan-ckan-1:5000/api/3/action/status_show"]
      interval: 60s
      timeout: 10s
      retries: 3  