[uwsgi]
# --- RED Y PUERTO ---
http            = 0.0.0.0:8800
# buffer-size debe ser menor a 65535 en algunas versiones de uWSGI
buffer-size     = 32768      # Aumentado para manejar cabeceras grandes

# --- IDENTIDAD Y RUTAS ---
uid             = datapusher
gid             = datapusher  # Corregido: es gid, no guid
chdir           = /srv/app/datapusher-src
wsgi-file       = /srv/app/datapusher-src/deployment/datapusher.wsgi
virtualenv      = /srv/app/datapusher-src
callable        = application

# --- CONFIGURACIÓN ---
env				= DATAPUSHER_SETTINGS=/srv/app/datapusher-src/deployment/datapusher_settings.py
env = PYTHONWARNINGS=ignore


# --- CONCURRENCIA (ESTABILIDAD) ---
master          = true
processes       = 1         # DataPusher es pesado, no pongas demasiados workers
threads         = 2         # Permite varias subtareas por worker
enable-threads  = true
lazy-apps       = true      # Evita errores de base de datos entre workers
thunder-lock    = true      # Evita el "thundering herd" en el socket

# --- TIEMPOS Y AUTORECUPERACIÓN ---
harakiri        = 1800      # ¡Crucial! 30 minutos para archivos gigantes
harakiri-verbose = true
http-timeout    = 1800
socket-timeout  = 1800

# --- GESTIÓN DE RECURSOS ---
max-requests    = 500       # Reinicia frecuentemente para liberar RAM (DataPusher fuga memoria)
vacuum          = true
pidfile         = /tmp/%n.pid
post-buffering  = 32768     # Buffer mayor para subidas de archivos



