networks:
  net-db:
    driver: bridge  
    external: true     
    
volumes:
  pg_data:  
  
services:

  db:
    build:
      context: postgres-image/
      dockerfile: Dockerfile
    image: CKAN/postgres:15    
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - CKAN_DB_USER
      - CKAN_DB_PASSWORD
      - CKAN_DB
      - DATASTORE_READONLY_USER
      - DATASTORE_READONLY_PASSWORD
      - DATASTORE_DB
      - CKAN_ALCALA_DB
    env_file:
      - .env  
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - net-db    
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_PASSWORD}"]  