networks:
  net-db:
    driver: bridge  
    external: true     
    
volumes:
  pg_data:  
  
services:

  db:
    build:
      context: postgres-image/
      dockerfile: Dockerfile
    image: CKAN/postgres:15    
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - CKAN_DB_USER
      - CKAN_DB_PASSWORD
      - CKAN_DB
      - DATASTORE_READONLY_USER
      - DATASTORE_READONLY_PASSWORD
      - CKAN_ARGELIA_DB=argelia_ckan_default
      - DATASTORE_ARGELIA_DB=argelia_datastore_default
      - DATASTORE_ALCALA_DB
      - CKAN_ALCALA_DB
      - CKAN_BOLIVAR_DB
      - DATASTORE_BOLIVAR_DB
      - CKAN_EL_AGUILA_DB
      - DATASTORE_EL_AGUILA_DB
      - CKAN_EL_CERRITO_DB
      - DATASTORE_EL_CERRITO_DB
      - CKAN_GUACARI_DB
      - DATASTORE_GUACARI_DB
      - CKAN_LA_VICTORIA_DB
      - DATASTORE_LA_VICTORIA_DB 
      - CKAN_PRADERA_DB
      - DATASTORE_PRADERA_DB
      - CKAN_RIOFRIO_DB
      - DATASTORE_RIOFRIO_DB
      - CKAN_SAN_PEDRO_DB
      - DATASTORE_SAN_PEDRO_DB
      - CKAN_TRUJILLO_DB
      - DATASTORE_TRUJILLO_DB
      - CKAN_ULLOA_DB
      - DATASTORE_ULLOA_DB
      - CKAN_VIJES_DB
      - DATASTORE_VIJES_DB
      - CKAN_YOTOCO_DB
      - DATASTORE_YOTOCO_DB
    env_file:
      - .env  
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - net-db    
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_PASSWORD}"]  